version: '3'
services: 
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: pgpass
      DBS: "prod preprod staging int dev"
      DB_SCALE: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
volumes:
  pgdata: